### primer get, hola mundo
GET http://localhost:3000

### get cats
GET http://localhost:3000/cats

### get cats
GET http://localhost:3000/cats/docs

### post cats
POST http://localhost:3000/cats
Content-Type: application/json

{
    "name":"Tom",
    "age":25,
    "breed":"Not"
}

### get dogs
GET http://localhost:3000/dogs

### post dogs
POST http://localhost:3000/dogs

### get dogs por id
GET http://localhost:3000/dogs/1a
